#include <pcl/point_types.h>
#include <pcl/impl/instantiate.hpp>
#include <pcl/features/sgf1.h>
#include <pcl/features/sgf2.h>
#include <pcl/features/sgf3.h>
#include <pcl/features/sgf4.h>
#include <pcl/features/sgf5.h>
#include <pcl/features/sgf6.h>
#include <pcl/features/sgf7.h>
#include <pcl/features/sgf8.h>
#include <pcl/features/sgf9.h>
#include <pcl/features/sgfall.h>

PCL_INSTANTIATE(SGF1Estimation, PCL_XYZ_POINT_TYPES);
PCL_INSTANTIATE(SGF2Estimation, PCL_XYZ_POINT_TYPES);
PCL_INSTANTIATE(SGF3Estimation, PCL_XYZ_POINT_TYPES);
PCL_INSTANTIATE(SGF4Estimation, PCL_XYZ_POINT_TYPES);
PCL_INSTANTIATE(SGF5Estimation, PCL_XYZ_POINT_TYPES);
PCL_INSTANTIATE(SGF6Estimation, PCL_XYZ_POINT_TYPES);
PCL_INSTANTIATE(SGF7Estimation, PCL_XYZ_POINT_TYPES);
PCL_INSTANTIATE(SGF8Estimation, PCL_XYZ_POINT_TYPES);
PCL_INSTANTIATE(SGF9Estimation, PCL_XYZ_POINT_TYPES);
PCL_INSTANTIATE(SGFALLEstimation, PCL_XYZ_POINT_TYPES);
